languageCode: 'en-us'
title: 'Latvian songs ABC notation'
theme: 'PaperMod'
preserveTaxonomyNames: true
menu:
  main:
    - identifier: "categories"
      name: "Artists"
      url: "/categories/"
      weight: 10
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 20
    - identifier: "akordi"
      name: "Akordi.lv"
      url: "https://www.akordi.lv"
      weight: 30
params:
  robotsNoIndex: true
  env: development # Set to development to have noindex in meta robots tag