baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Latvian songs ABC notation'
theme = 'PaperMod'
preserveTaxonomyNames = true
[[menu.main]]
    identifier = "categories"
    name = "Artists"
    url = "/categories/"
    weight = 10

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20

[[menu.main]]
    identifier = "akordi"
    name = "Akordi.lv"
    url = "https://www.akordi.lv"
    weight = 30