name: Nightly Download

on:
  schedule:
    - cron: '0 2 * * *' # 2 AM UTC every day
  workflow_dispatch:

jobs:
  go-run:
    runs-on: ubuntu-latest
    container: golang:1.25 # Use the Go Docker image

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Run download.go
      run: go run download.go

    - name: Mark repository as safe directory
      run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'bot@github.com'
        git add .
        git commit -m "Update downloaded files" || echo "No changes to commit"
        git push
